/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define GETTEXT_PACKAGE "gnome-screenshot"

#define HAVE_X11_EXTENSIONS_SHAPE_H 1

#define VERSION "3.36.0"

